### ISSUE TITLE
Update documentation to use `rule` instead of `iptables_rule`

### ISSUE THREAD

**Issue by kenmacleod** [chef-cookbooks/iptables#100]
`iptables_rule` was changed to `rule` in 1.0 (per the README) but the examples still say `iptables_rule`.

On a side note, it's unfortunate that this cookbook takes such a generic resource name `rule`.  It may have been better as `iptable_rule` when it was converted to a custom resource.

**Comment by devsibwarra** [comment]
This cookbook defines custom resources `iptables_rule` and `iptables_rule6`

Please review the [Chef Custom Resources](https://docs.chef.io/custom_resources.html) documentation for additional info
