### ISSUE TITLE
Can't use INPUT chain on the filter table when using this cookbook?

### ISSUE THREAD

**Issue by Maniacal** [chef-cookbooks/iptables#23]
I was trying to add a rule for ssh which I put into my template like:

-A INPUT -p tcp --dport 22 -j ACCEPT

But it appears as if this rule:  -A INPUT -j FWR trumps my rule and sends everything to the FWR chain.  My rule works if I put '-A FWR' instead but the documentation isn't clear that that is required when using this cookbook.

Am I doing something wrong?  Is it possible to add to the INPUT chain in the filter table?

Whatever the answer is I'll follow up with a pull request to make the documentation more clear (unless it's there and I'm just missing it)

Thanks,

MG

**Comment by lamont-granquist** [comment]
this has been open for nearly 2 years, i hope you eventually figured it out by now....
