### ISSUE TITLE
default recipe doesn't ensure iptables service is enabled

### ISSUE THREAD

**Issue by docwhat** [chef-cookbooks/iptables#26]
If you use the `disable` recipe and then run the `default` recipe, the `iptables` service isn't re-enabled.  If a system is rebooted, the iptables rules aren't applied.

Currently, it looks like the "restarting" of the iptables is handled in the rebuild-iptables.  But it isn't re-enabled there.

**Comment by tas50** [comment]
The service itself should get managed and this is an issue at the moment.  I'll dig in and check on the various names for the service itself and see if I can add this in for the 1.1 release
