### ISSUE TITLE
Example provided for 80 -> 8080 redirect fails on ubuntu14

### ISSUE THREAD

**Issue by zarry** [chef-cookbooks/iptables#28]
The example in your readme for redirect traffic from port 80 to 8080 does not work.  It looks like this issue was filed once years ago when jira was still the place.

https://tickets.opscode.com/browse/COOK-1004

I am currently running into this exact same issue following the steps outlined in your readme.  Is the solution really what is described in the ticket?  Why would this be the example listed in the readme then? Am I missing something? 

```
[2015-01-29T15:53:39-05:00] ERROR: execute[rebuild-iptables] (iptables::default line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '25'
---- Begin output of /usr/sbin/rebuild-iptables ----
STDOUT:
STDERR: Bad argument `*nat'
Error occurred at line: 14
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
rebuild-iptables: iptables-restore failed! - 512 at /usr/sbin/rebuild-iptables line 134.
---- End output of /usr/sbin/rebuild-iptables ----
Ran /usr/sbin/rebuild-iptables returned 25
       [2015-01-29T15:53:39-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by lamont-granquist** [comment]
followed the README instructions on 1404 and it just worked fine.  don't know if this bug got fixed in the past 18 months or if there was some other issue, but can't replicate, so closing
