### ISSUE TITLE
Can we move the iptables-rebuild script into a ruby library?

### ISSUE THREAD

**Issue by lamont-granquist** [chef-cookbooks/iptables#67]
@thommay @tas50 @iennae am I missing something here?  Does this have to be an external command API for some reason?

It seems like we drop the file on the filesystem and then only ever execute it from this cookbook -- we could move it to a library and then ruby_block it and i can't see what would change (other than we could properly use shell_out! and avoid shebang-hell and maybe write a real resource for what it does?)

**Comment by lamont-granquist** [comment]
even if we turn it into a resource, we can also most likely leave a chef-client override-run-list script in its place (i think we'd need to do that since wiring up chef-apply/chef-solo/chef-zolo to the cookbook store where the iptables cookbook is would be fraught with peril).

**Comment by tas50** [comment]
I suspect this was something that made sense to someone back in the day. At this point it seems like we should be doing it via a library.

**Comment by iennae** [comment]
+1 to library.

**Comment by lamont-granquist** [comment]
need to replace `system` with `shell_out!` everywhere

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.

**Comment by bmhughes** [comment]
Got this working pretty well now as an accumulated template in the rule resources to create the persistent rule files directly. 

Got some tidying up and documentation to do so unless anything catches fire shortly I should have a PR ready by the end of this week hopefully.

**Comment by Xorima** [comment]
Closing as we have the accumulator pattern on this cookbook now, please re-open if there are still changes we want to see done (Or open a new ticket?)
