### ISSUE TITLE
No resource or method named `iptables_rule' for `Chef::Recipe "default"'

### ISSUE THREAD

**Issue by hagay3** [chef-cookbooks/iptables#70]
### Cookbook version
3.0.1

### Chef-client version
12.17.44, tried also 12.9.41

### Platform Details
ubuntu-1204

### Scenario:
Trying to converge kitchen instance for the first time

### Steps to Reproduce:
1. clone the cookbook
2. kitchen converge default-ubuntu-1204

### Expected Result:
Kitchen instance installed with the rule ssh

### Actual Result:
Chef fails on No resource or method named `iptables_rule' for `Chef::Recipe "default"'
error output:
https://gist.github.com/hagay3/e6a82a7a5188c03e351af2a7638d64b5

**Comment by hagay3** [comment]
Ok sorry for the inconvenience.
Seems like the issue happened because I changed the cookbook name.
The think is I changed every where it mentioned so I dont know why it is a problem.

**Comment by tas50** [comment]
Just a heads up if you add a provides line to https://github.com/chef-cookbooks/iptables/blob/master/resources/rule.rb you can avoid having to rename everything. The cookbook can be names whatever but the resource will still provide 'iptables_rule' https://docs.chef.io/custom_resources.html#provides
